# Generated by Django 5.2.7 on 2025-11-04 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='status',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='uploaded_by',
        ),
    ]
