# Generated by Django 5.2.7 on 2025-11-12 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('design', '0002_initial'),
        ('papers', '0001_initial'),
        ('projects', '0003_alter_researchproject_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('double_extraction', models.BooleanField(default=False)),
                ('auto_close', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_phase', to='projects.researchproject')),
            ],
            options={
                'verbose_name': 'Extraction Phase',
                'verbose_name_plural': 'Extraction Phases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pendiente'), ('InProgress', 'En Progreso'), ('Done', 'Completado')], db_index=True, default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, help_text="Fecha en que se cambió el estado a 'In Progress'", null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text="Fecha en que se marcó como 'Done'", null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas internas del researcher sobre este paper')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Researcher asignado a este paper', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_extractions', to=settings.AUTH_USER_MODEL)),
                ('paper', models.OneToOneField(help_text='Paper al que pertenece este registro de extracción', on_delete=django.db.models.deletion.CASCADE, related_name='extraction', to='papers.paper')),
            ],
            options={
                'verbose_name': 'Paper Extraction',
                'verbose_name_plural': 'Paper Extractions',
                'ordering': ['-last_modified'],
            },
        ),
        migrations.CreateModel(
            name='ErrorHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_tags', models.JSONField(blank=True, default=list, help_text='Lista de tags obligatorios que faltan')),
                ('message', models.TextField(help_text='Mensaje descriptivo del error')),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha en que se envió la notificación', null=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Indica si el error ha sido corregido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='Usuario que debe ser notificado', on_delete=django.db.models.deletion.CASCADE, related_name='extraction_errors', to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_errors', to='extraction.paperextraction')),
            ],
            options={
                'verbose_name': 'Error Handler',
                'verbose_name_plural': 'Error Handlers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, default='#FFFFFF', help_text='Color hexadecimal para visualización', max_length=50)),
                ('justification', models.TextField(blank=True, help_text='Definición y criterios de aplicación del tag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('deductive', 'Deductivo'), ('inductive', 'Inductivo')], default='deductive', max_length=20)),
                ('is_mandatory', models.BooleanField(default=False, help_text='Si es obligatorio aplicar este tag (automático si tiene question)')),
                ('is_public', models.BooleanField(default=True, help_text='Si es visible para los investigadores')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tags', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(blank=True, help_text='Pregunta de investigación asociada (si es deductivo)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='design.researchquestion')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_portion', models.TextField(help_text='Fragmento textual extraído del paper')),
                ('location', models.CharField(blank=True, help_text='Ubicación en el paper (página, sección, etc.)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated', models.BooleanField(default=False, help_text='Indica si la quote ha sido validada por un revisor')),
                ('paper_extraction', models.ForeignKey(help_text='Extracción a la que pertenece esta quote', on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='extraction.paperextraction')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='quotes', to='extraction.tag')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_review', models.BooleanField(db_index=True, default=False, help_text='Indica si es parte de una revisión formal')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='extraction__content_40258b_idx'), models.Index(fields=['user', 'created_at'], name='extraction__user_id_e1efd8_idx'), models.Index(fields=['is_review', 'created_at'], name='extraction__is_revi_da2ce9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paperextraction',
            index=models.Index(fields=['status', 'assigned_to'], name='extraction__status_354ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='paperextraction',
            index=models.Index(fields=['status', 'last_modified'], name='extraction__status_1b48ab_idx'),
        ),
        migrations.AddIndex(
            model_name='paperextraction',
            index=models.Index(fields=['assigned_to', 'status'], name='extraction__assigne_265059_idx'),
        ),
        migrations.AddIndex(
            model_name='errorhandler',
            index=models.Index(fields=['is_resolved', 'created_at'], name='extraction__is_reso_0d02b2_idx'),
        ),
        migrations.AddIndex(
            model_name='errorhandler',
            index=models.Index(fields=['user', 'is_resolved'], name='extraction__user_id_ad7395_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['type', 'is_mandatory'], name='extraction__type_a51360_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['is_public', 'type'], name='extraction__is_publ_c17dc4_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'question'), name='unique_tag_name_per_question'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['validated', 'created_at'], name='extraction__validat_0ebb83_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['researcher', 'created_at'], name='extraction__researc_79dfb0_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['paper_extraction', 'validated'], name='extraction__paper_e_baf86e_idx'),
        ),
    ]
