# Generated by Django 5.2.7 on 2025-11-04 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0002_initial'),
        ('papers', '0004_remove_paper_status_remove_paper_uploaded_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'In Progress'), ('Done', 'Done')], default='Pending', max_length=50)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_assignments', to=settings.AUTH_USER_MODEL)),
                ('papers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_record', to='papers.papers')),
            ],
            options={
                'verbose_name': 'Extraction Record',
                'verbose_name_plural': 'Extraction Records',
            },
        ),
        migrations.AlterField(
            model_name='errorhandler',
            name='papers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_errors', to='extraction.extractionrecord'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='papers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='extraction.extractionrecord'),
        ),
    ]
