# Generated by Django 5.2.7 on 2025-11-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchproject',
            name='status',
            field=models.CharField(choices=[('DesignActive', 'DesignActive'), ('ExtractionActive', 'Extraction Active'), ('Closed', 'Closed')], db_index=True, default='DesignActive', max_length=20),
        ),
    ]
